In [2]:
import torch
print(torch.__version__)

2.4.1+cpu


## Tensors

In [13]:
scalar = torch.tensor([3,4])
scalar

tensor([3, 4])

In [23]:
s1 = torch.tensor([3.,4.],requires_grad=True)
o1 = s1.pow(2).sum()
print(o1)
o1.backward()
# print(o1)
print(s1.grad)

tensor(25., grad_fn=<SumBackward0>)
tensor([6., 8.])


In [26]:
s2 = torch.tensor([[3,3,1],[3,2,1]])
print(s2.shape)
print(s2.ndim)

torch.Size([2, 3])
2


## Random Tensors

because

`start with random -> look the data -> update the numbers -> look the data ....`

In [3]:
r1 = torch.rand(3,4)
r1

tensor([[0.0869, 0.9520, 0.1970, 0.5299],
        [0.2518, 0.9227, 0.2297, 0.2108],
        [0.1499, 0.5448, 0.1573, 0.1878]])

In [4]:
z1 = torch.zeros(size=(3,4))
z1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
o2 = torch.ones(size=(3,4))
o2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Torch with arange

In [8]:
torch.arange(0,40,5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35])

In [9]:
torch.arange(start=5, end=15, step=2)

tensor([ 5,  7,  9, 11, 13])

In [10]:
## Tensors like
torch.zeros_like(o2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## datatypes

In [12]:
a1 = torch.tensor([1,2,3],dtype=torch.int32)
a1,a1.dtype

(tensor([1, 2, 3], dtype=torch.int32), torch.int32)

In [13]:
def summary(p):
    print(f"Dtype: {p.dtype}")
    print(f"shape: {p.shape}")
    print(f"Device: {p.device}")

In [18]:
a2 = torch.tensor([1,2,3])
a2

tensor([1, 2, 3])

## Tensor menipulation

* Add
* Mul
* sub
* div
* matrix mul

In [19]:
t1 = torch.tensor([1,2,3])

In [20]:
t1+10, torch.add(t1,10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [21]:
t1*10, torch.mul(t1,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [24]:
# elementwise multiplication
t1*t1, torch.mul(t1,t1)

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [34]:
%%time
# matrix multiplication
torch.matmul(t1,t1) ## gives a dot product for a vector or a n*1 or 1*n shape

CPU times: user 145 μs, sys: 78 μs, total: 223 μs
Wall time: 245 μs


tensor(14)

In [29]:
%%time
value = 0
for i in t1:
    value += i*i
value

CPU times: user 4.64 ms, sys: 3.86 ms, total: 8.5 ms
Wall time: 5.26 ms


tensor(14)

In [33]:
%%time
t1@t1

CPU times: user 55 μs, sys: 30 μs, total: 85 μs
Wall time: 90.4 μs


tensor(14)

In [36]:
%%time
torch.rand(4,5) @ torch.rand(5,3)

CPU times: user 1.23 ms, sys: 96 μs, total: 1.32 ms
Wall time: 1.12 ms


tensor([[0.9712, 1.5431, 1.0640],
        [1.0893, 1.4020, 1.1188],
        [0.9706, 1.3117, 0.8028],
        [1.2982, 1.8818, 1.3276]])

In [37]:
t2 = torch.rand(3,2)
t2.T@t2

tensor([[0.7294, 0.5871],
        [0.5871, 0.8027]])

## tensor aggregation
### min, max, sum, mean, etc

In [41]:
t1.sum(), t1.min(), torch.mean(t1.type(torch.float64))

(tensor(6), tensor(1), tensor(2., dtype=torch.float64))

In [47]:
## argmax is to find the position of element having the max value
torch.tensor([1,3,2]).argmax()

tensor(1)

## reshaping, stacking, squeezing and unsqueezing tensors

* rashaping
* view
* stacking - removes 1 dim
* squeezing - adds 1 dim
* unsqueezing
* permute

In [48]:
t1 = torch.tensor([1,2,3,4])

In [50]:
t1.reshape(1,4), t1.reshape(2,2)

(tensor([[1, 2, 3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [60]:
torch.stack([t1,t1,t1,t1], dim=1)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [63]:
t2 = torch.rand(255,255,3) # shape is 255 * 255 * 3
t2 = t2.permute(2,0,1) # meaning makes it 3 * 255 * 255
t2.shape

torch.Size([3, 255, 255])

## indexing and selecting

In [70]:
t1 = torch.arange(1,10).reshape(3,3)

In [71]:
t1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
t1[0]

tensor([1, 2, 3])

In [73]:
t1[0,0]

tensor(1)

In [76]:
t1[:,1] ## every row and 2nd column

tensor([2, 5, 8])

## pytorch and numpy

* numpy to torch ==> torch.from_numpy(ndarray)
* torch to numpy ==> torch.Tensor.numpy()

## reproducibility

we use random seed to flavour randomness

In [80]:
## manual seed
seed = 42

torch.manual_seed(seed)
t1 = torch.rand(1,3)


torch.manual_seed(seed)
t2 = torch.rand(1,3)

print(t1 == t2)


torch.manual_seed(seed)
t1 = torch.rand(1,3)
t2 = torch.rand(1,3)

print(t1 == t2)

tensor([[True, True, True]])
tensor([[False, False, False]])
