In [2]:
import pandas as pd
import numpy as np
import torch
from torch import nn

In [101]:
train_data = torch.tensor([[[1],[0]],[[1],[1]],[[0],[0]],[[0],[1]]], dtype=torch.float) # in_features = 2 
train_labels = torch.tensor([[0],[1],[1],[0]], dtype=torch.float) # out_features = 1

In [88]:
train_data.shape, train_labels.shape

(torch.Size([4, 2, 1]), torch.Size([4, 1]))

In [4]:
def display_frame(data,*args):
    temp = pd.DataFrame(data)
    for temp_1 in args:
        temp.insert(temp.shape[1], temp.shape[1], temp_1)
    print(temp)
    
# train_df = pd.DataFrame(train_data.numpy())
# train_df.insert(train_df.shape[1],"labels", train_labels.numpy())
# train_df

display_frame(train_data,train_labels)

     0    1    2
0  1.0  0.0  0.0
1  1.0  1.0  1.0
2  0.0  0.0  1.0
3  0.0  1.0  0.0


In [117]:
class Model(nn.Module):
    def __init__(self,in_f,out_f):
        super(Model,self).__init__()
        
        self.conv1 = nn.Conv1d(in_f,10, kernel_size=1,stride=1)
        self.conv2 = nn.Conv1d(10,out_f, kernel_size=1,stride=1)
        self.relu = nn.ReLU()

    def forward(self,x):
        print("Model: ")
        print("Shape of x: ",x.shape)
        x = self.conv1(x)
        print("Shape of x after conv1: ", x.shape)
        x = self.conv2(x)
        print("Shape of x after conv2: ", x.shape)
        x = self.relu(x)
        return x

In [127]:
torch.manual_seed(45)
model = Model(2,1)

In [128]:
list(model.parameters())

[Parameter containing:
 tensor([[[-0.4427],
          [ 0.6524]],
 
         [[ 0.2594],
          [ 0.5640]],
 
         [[-0.6357],
          [ 0.0784]],
 
         [[ 0.4046],
          [-0.6270]],
 
         [[ 0.4019],
          [-0.4978]],
 
         [[-0.6522],
          [-0.5604]],
 
         [[-0.1108],
          [-0.3715]],
 
         [[ 0.4399],
          [ 0.0481]],
 
         [[ 0.2593],
          [ 0.2161]],
 
         [[ 0.1588],
          [ 0.6836]]], requires_grad=True),
 Parameter containing:
 tensor([-0.4489, -0.5319, -0.1043,  0.6670,  0.1764,  0.3991, -0.1276, -0.2163,
         -0.3063,  0.3565], requires_grad=True),
 Parameter containing:
 tensor([[[-0.0868],
          [ 0.0786],
          [ 0.2257],
          [ 0.1842],
          [-0.1231],
          [-0.2924],
          [ 0.1745],
          [-0.1165],
          [-0.2151],
          [ 0.0530]]], requires_grad=True),
 Parameter containing:
 tensor([-0.0107], requires_grad=True)]

In [80]:
list(model.parameters())

[Parameter containing:
 tensor([[[0.5281],
          [0.6066]]], requires_grad=True),
 Parameter containing:
 tensor([-0.1716], requires_grad=True)]

In [21]:
print(model.linear_1.weight)
print(model.linear_1.bias)

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496]], requires_grad=True)
Parameter containing:
tensor([-0.1549,  0.1427], requires_grad=True)


In [108]:
from torchsummary import summary
summary(model, input_size=(2,1))

Model: 
Shape of x:  torch.Size([2, 2, 1])
Shape of x after conv1:  torch.Size([2, 2, 1])
Shape of x after conv2:  torch.Size([2, 1, 1])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv1d-1                 [-1, 2, 1]               6
            Conv1d-2                 [-1, 1, 1]               3
Total params: 9
Trainable params: 9
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [67]:
torch.rand(1,2,2)

tensor([[[0.9593, 0.3904],
         [0.6009, 0.2566]]])

In [93]:
loss_fn = nn.L1Loss()
# optimizer = torch.optim.SGD(params=model.parameters(), lr=0.01)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
# loss_fn = nn.CrossEntropyLoss()

In [94]:

y_pred = model(train_data[1])
y_pred.squeeze(dim=0), train_labels[1], loss_fn(y_pred.squeeze(dim=0), train_labels[0])

(tensor([0.9950], grad_fn=<SqueezeBackward1>),
 tensor([1.]),
 tensor(0.0050, grad_fn=<MeanBackward0>))

In [124]:
epochs = 1000

for i in range(epochs):
    # for j in range(4):
    model.train()

    y_pred = model(train_data)

    loss = loss_fn(y_pred.squeeze(dim=0),train_labels)
    print(loss)

    optimizer.zero_grad()
    
    loss.backward()

    optimizer.step()

    model.eval()
    

Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after conv2:  torch.Size([4, 1, 1])
tensor(0.5000, grad_fn=<MeanBackward0>)
Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after conv2:  torch.Size([4, 1, 1])
tensor(0.5000, grad_fn=<MeanBackward0>)
Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after conv2:  torch.Size([4, 1, 1])
tensor(0.5000, grad_fn=<MeanBackward0>)
Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after conv2:  torch.Size([4, 1, 1])
tensor(0.5000, grad_fn=<MeanBackward0>)
Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after conv2:  torch.Size([4, 1, 1])
tensor(0.5000, grad_fn=<MeanBackward0>)
Model: 
Shape of x:  torch.Size([4, 2, 1])
Shape of x after conv1:  torch.Size([4, 10, 1])
Shape of x after co

In [121]:
with torch.no_grad():
    for i in range(4):
        y_pred = model(train_data[i])
        print(y_pred)
train_labels

Model: 
Shape of x:  torch.Size([2, 1])
Shape of x after conv1:  torch.Size([10, 1])
Shape of x after conv2:  torch.Size([1, 1])
tensor([[0.2795]])
Model: 
Shape of x:  torch.Size([2, 1])
Shape of x after conv1:  torch.Size([10, 1])
Shape of x after conv2:  torch.Size([1, 1])
tensor([[0.3733]])
Model: 
Shape of x:  torch.Size([2, 1])
Shape of x after conv1:  torch.Size([10, 1])
Shape of x after conv2:  torch.Size([1, 1])
tensor([[0.]])
Model: 
Shape of x:  torch.Size([2, 1])
Shape of x after conv1:  torch.Size([10, 1])
Shape of x after conv2:  torch.Size([1, 1])
tensor([[0.0097]])


tensor([[0.],
        [1.],
        [1.],
        [0.]])

In [16]:
test_data = torch.tensor([[1,1]], dtype=torch.float)
test_labels = torch.tensor([[1]], dtype=torch.float)

In [17]:
with torch.no_grad():
    y_pred = model(test_data)
print(y_pred, test_labels)

Model: 
Shape of x:  torch.Size([1, 2])
Shape of x after linear_1:  torch.Size([1, 100])
Shape of x after relu:  torch.Size([1, 100])
Shape of x after linear_2:  torch.Size([1, 1])
Shape of x after relu:  torch.Size([1, 1])
tensor([[0.]]) tensor([[1.]])
